services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '6000:6000'
    depends_on:
      - auth
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
        - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest